INFO 2024-05-07 23:50:31,155 autoreload 8328 9532 Watching for file changes with StatReloader
INFO 2024-05-07 23:51:05,740 basehttp 8328 13708 "GET /game/random_num/ HTTP/1.1" 200 49
INFO 2024-05-07 23:51:10,315 basehttp 8328 13708 "GET /game/random_num/ HTTP/1.1" 200 48
INFO 2024-05-07 23:51:24,075 basehttp 8328 13708 "GET /game/cube/ HTTP/1.1" 200 93
INFO 2024-05-07 23:51:29,650 basehttp 8328 13708 "GET /game/cube/ HTTP/1.1" 200 93
INFO 2024-05-07 23:57:58,902 basehttp 8328 3904 "GET /prefix/ HTTP/1.1" 200 14
INFO 2024-05-07 23:59:32,347 autoreload 10916 9064 Watching for file changes with StatReloader
INFO 2024-05-08 00:01:34,023 basehttp 10916 544 "GET /prefix/ HTTP/1.1" 200 14
INFO 2024-05-08 00:01:44,564 basehttp 10916 544 "GET /prefix/about/ HTTP/1.1" 200 27
INFO 2024-05-08 12:41:54,189 autoreload 10916 9064 C:\Users\A9219\PycharmProjects\Django\seminar_proj\seminarapp\views.py changed, reloading.
INFO 2024-05-08 12:41:55,022 autoreload 15168 6872 Watching for file changes with StatReloader
INFO 2024-05-08 12:42:05,726 basehttp 15168 15016 "GET /prefix/ HTTP/1.1" 200 41
WARNING 2024-05-08 12:42:06,207 log 15168 15016 Not Found: /favicon.ico
INFO 2024-05-08 12:42:06,207 basehttp 15168 15016 - Broken pipe from ('127.0.0.1', 52971)
INFO 2024-05-08 12:44:21,867 autoreload 15168 6872 C:\Users\A9219\PycharmProjects\Django\seminar_proj\seminarapp\views.py changed, reloading.
INFO 2024-05-08 12:44:22,738 autoreload 1864 7380 Watching for file changes with StatReloader
INFO 2024-05-08 12:45:40,460 autoreload 1864 7380 C:\Users\A9219\PycharmProjects\Django\seminar_proj\seminarapp\views.py changed, reloading.
INFO 2024-05-08 12:45:41,662 autoreload 6100 12608 Watching for file changes with StatReloader
INFO 2024-05-08 12:45:42,937 basehttp 6100 12212 "GET /prefix/ HTTP/1.1" 200 41
INFO 2024-05-08 12:45:56,072 basehttp 6100 12212 "GET /prefix/ HTTP/1.1" 200 41
INFO 2024-05-08 12:45:56,677 autoreload 6100 12608 C:\Users\A9219\PycharmProjects\Django\seminar_proj\seminarapp\views.py changed, reloading.
INFO 2024-05-08 12:45:57,800 autoreload 11796 14752 Watching for file changes with StatReloader
INFO 2024-05-08 12:45:59,916 basehttp 11796 1144 "GET /prefix/ HTTP/1.1" 200 70
INFO 2024-05-08 12:47:11,310 basehttp 11796 1144 "GET /prefix/ HTTP/1.1" 200 70
INFO 2024-05-08 12:48:32,806 basehttp 11796 1144 "GET /prefix/about/ HTTP/1.1" 200 27
INFO 2024-05-08 12:53:56,404 autoreload 11796 14752 C:\Users\A9219\PycharmProjects\Django\seminar_proj\seminarapp\views.py changed, reloading.
INFO 2024-05-08 12:53:57,392 autoreload 12344 9592 Watching for file changes with StatReloader
ERROR 2024-05-08 12:54:02,130 log 12344 15184 Internal Server Error: /prefix/about/
Traceback (most recent call last):
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view seminarapp.views.about didn't return an HttpResponse object. It returned None instead.
ERROR 2024-05-08 12:54:02,130 basehttp 12344 15184 "GET /prefix/about/ HTTP/1.1" 500 70444
ERROR 2024-05-08 12:54:17,172 log 12344 15184 Internal Server Error: /prefix/about/
Traceback (most recent call last):
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view seminarapp.views.about didn't return an HttpResponse object. It returned None instead.
ERROR 2024-05-08 12:54:17,188 basehttp 12344 15184 "GET /prefix/about/ HTTP/1.1" 500 70444
INFO 2024-05-08 12:54:17,525 autoreload 12344 9592 C:\Users\A9219\PycharmProjects\Django\seminar_proj\seminarapp\views.py changed, reloading.
INFO 2024-05-08 12:54:18,454 autoreload 2224 15296 Watching for file changes with StatReloader
INFO 2024-05-08 12:54:21,744 basehttp 2224 14764 "GET /prefix/about/ HTTP/1.1" 200 160
INFO 2024-05-08 12:54:41,057 basehttp 2224 14764 "GET /prefix/about/ HTTP/1.1" 200 160
INFO 2024-05-08 12:54:41,799 autoreload 2224 15296 C:\Users\A9219\PycharmProjects\Django\seminar_proj\seminarapp\views.py changed, reloading.
INFO 2024-05-08 12:54:42,589 autoreload 3784 6292 Watching for file changes with StatReloader
INFO 2024-05-08 12:54:44,394 basehttp 3784 12836 "GET /prefix/about/ HTTP/1.1" 200 163
INFO 2024-05-08 12:55:14,174 autoreload 3784 6292 C:\Users\A9219\PycharmProjects\Django\seminar_proj\seminarapp\views.py changed, reloading.
INFO 2024-05-08 12:55:15,027 autoreload 11004 8520 Watching for file changes with StatReloader
INFO 2024-05-08 12:55:19,751 basehttp 11004 8372 "GET /prefix/about/ HTTP/1.1" 200 173
INFO 2024-05-08 12:55:53,645 autoreload 11004 8520 C:\Users\A9219\PycharmProjects\Django\seminar_proj\seminarapp\views.py changed, reloading.
INFO 2024-05-08 12:55:54,547 autoreload 13688 14488 Watching for file changes with StatReloader
INFO 2024-05-08 12:55:57,194 basehttp 13688 11212 "GET /prefix/about/ HTTP/1.1" 200 170
INFO 2024-05-08 12:56:28,006 autoreload 13688 14488 C:\Users\A9219\PycharmProjects\Django\seminar_proj\seminarapp\views.py changed, reloading.
INFO 2024-05-08 12:56:29,043 autoreload 13320 9392 Watching for file changes with StatReloader
INFO 2024-05-08 12:56:51,208 autoreload 13320 9392 C:\Users\A9219\PycharmProjects\Django\seminar_proj\seminarapp\views.py changed, reloading.
INFO 2024-05-08 12:56:52,179 autoreload 12004 14612 Watching for file changes with StatReloader
INFO 2024-05-08 12:56:55,124 basehttp 12004 13864 "GET /prefix/about/ HTTP/1.1" 200 189
INFO 2024-05-08 12:57:05,150 autoreload 12004 14612 C:\Users\A9219\PycharmProjects\Django\seminar_proj\seminarapp\views.py changed, reloading.
INFO 2024-05-08 12:57:06,019 autoreload 10688 10992 Watching for file changes with StatReloader
INFO 2024-05-08 12:57:12,633 autoreload 10688 10992 C:\Users\A9219\PycharmProjects\Django\seminar_proj\seminarapp\views.py changed, reloading.
INFO 2024-05-08 12:57:13,411 autoreload 7896 3812 Watching for file changes with StatReloader
WARNING 2024-05-08 15:20:10,999 log 7896 11716 Not Found: /
WARNING 2024-05-08 15:20:11,015 basehttp 7896 11716 "GET / HTTP/1.1" 404 2277
INFO 2024-05-08 15:21:02,771 autoreload 7896 3812 C:\Users\A9219\PycharmProjects\Django\seminar_proj\seminar_proj\urls.py changed, reloading.
INFO 2024-05-08 15:21:04,039 autoreload 9708 7160 Watching for file changes with StatReloader
INFO 2024-05-08 15:21:08,060 basehttp 9708 8736 "GET / HTTP/1.1" 200 70
INFO 2024-05-08 15:21:41,953 basehttp 9708 8736 "GET /about/ HTTP/1.1" 200 173
INFO 2024-05-08 15:49:19,554 basehttp 9708 5608 "GET /about/ HTTP/1.1" 200 173
INFO 2024-05-08 15:49:24,884 basehttp 9708 5608 "GET / HTTP/1.1" 200 70
INFO 2024-05-08 15:49:43,508 basehttp 9708 5608 "GET /game/cube/ HTTP/1.1" 200 93
INFO 2024-05-08 15:50:17,735 basehttp 9708 5608 "GET /game/random_num/ HTTP/1.1" 200 49
INFO 2024-05-08 15:51:56,089 autoreload 9708 7160 C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py changed, reloading.
INFO 2024-05-08 15:51:56,997 autoreload 13492 15332 Watching for file changes with StatReloader
WARNING 2024-05-08 15:52:28,122 log 13492 12156 Not Found: /game/
WARNING 2024-05-08 15:52:28,122 basehttp 13492 12156 "GET /game/ HTTP/1.1" 404 2962
INFO 2024-05-08 15:52:52,290 basehttp 13492 12156 "GET / HTTP/1.1" 200 70
INFO 2024-05-12 00:09:59,039 autoreload 1180 13148 Watching for file changes with StatReloader
INFO 2024-05-12 00:12:43,670 autoreload 14244 12656 Watching for file changes with StatReloader
INFO 2024-05-12 00:14:13,657 autoreload 14244 12656 C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py changed, reloading.
INFO 2024-05-12 00:14:14,503 autoreload 12840 9132 Watching for file changes with StatReloader
INFO 2024-05-12 00:17:49,281 autoreload 10464 15184 Watching for file changes with StatReloader
INFO 2024-05-12 00:18:43,995 autoreload 10464 15184 C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py changed, reloading.
INFO 2024-05-12 00:18:44,803 autoreload 13888 13924 Watching for file changes with StatReloader
INFO 2024-05-12 00:19:35,752 basehttp 13888 1156 "GET / HTTP/1.1" 200 70
ERROR 2024-05-12 00:20:07,179 log 13888 1156 Internal Server Error: /game/orel_reshka/
Traceback (most recent call last):
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py", line 14, in orel_reshka
    res.save()
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    for sql, params in self.as_sql():
                       ^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1745, in as_sql
    value_rows = [
                 ^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1746, in <listcomp>
    [
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1747, in <listcomp>
    self.prepare_value(field, self.pre_save_val(field, obj))
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1686, in prepare_value
    return field.get_db_prep_save(value, connection=self.connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 1013, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2610, in get_db_prep_value
    value = self.get_prep_value(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2605, in get_prep_value
    return self.to_python(value)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2579, in to_python
    parsed = parse_time(value)
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\utils\dateparse.py", line 95, in parse_time
    return datetime.time.fromisoformat(value).replace(tzinfo=None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: fromisoformat: argument must be str
ERROR 2024-05-12 00:20:07,300 basehttp 13888 1156 "GET /game/orel_reshka/ HTTP/1.1" 500 144113
INFO 2024-05-12 00:20:44,826 autoreload 13888 13924 C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py changed, reloading.
INFO 2024-05-12 00:20:46,007 autoreload 5968 10288 Watching for file changes with StatReloader
ERROR 2024-05-12 00:20:56,692 log 5968 11488 Internal Server Error: /game/orel_reshka/
Traceback (most recent call last):
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py", line 14, in orel_reshka
    res.save()
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    for sql, params in self.as_sql():
                       ^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1745, in as_sql
    value_rows = [
                 ^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1746, in <listcomp>
    [
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1747, in <listcomp>
    self.prepare_value(field, self.pre_save_val(field, obj))
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1686, in prepare_value
    return field.get_db_prep_save(value, connection=self.connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 1013, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2610, in get_db_prep_value
    value = self.get_prep_value(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2605, in get_prep_value
    return self.to_python(value)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2579, in to_python
    parsed = parse_time(value)
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\utils\dateparse.py", line 95, in parse_time
    return datetime.time.fromisoformat(value).replace(tzinfo=None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: fromisoformat: argument must be str
ERROR 2024-05-12 00:20:56,707 basehttp 5968 11488 "GET /game/orel_reshka/ HTTP/1.1" 500 144118
INFO 2024-05-12 00:21:34,961 autoreload 5968 10288 C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py changed, reloading.
INFO 2024-05-12 00:21:36,466 autoreload 13560 2436 Watching for file changes with StatReloader
ERROR 2024-05-12 00:21:40,699 log 13560 10236 Internal Server Error: /game/orel_reshka/
Traceback (most recent call last):
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py", line 14, in orel_reshka
    res.save()
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    for sql, params in self.as_sql():
                       ^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1745, in as_sql
    value_rows = [
                 ^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1746, in <listcomp>
    [
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1747, in <listcomp>
    self.prepare_value(field, self.pre_save_val(field, obj))
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1686, in prepare_value
    return field.get_db_prep_save(value, connection=self.connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 1013, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2610, in get_db_prep_value
    value = self.get_prep_value(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2605, in get_prep_value
    return self.to_python(value)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2579, in to_python
    parsed = parse_time(value)
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\utils\dateparse.py", line 95, in parse_time
    return datetime.time.fromisoformat(value).replace(tzinfo=None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: fromisoformat: argument must be str
ERROR 2024-05-12 00:21:40,730 basehttp 13560 10236 "GET /game/orel_reshka/ HTTP/1.1" 500 144130
ERROR 2024-05-12 00:21:43,875 log 13560 10236 Internal Server Error: /game/orel_reshka/
Traceback (most recent call last):
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py", line 14, in orel_reshka
    res.save()
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    for sql, params in self.as_sql():
                       ^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1745, in as_sql
    value_rows = [
                 ^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1746, in <listcomp>
    [
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1747, in <listcomp>
    self.prepare_value(field, self.pre_save_val(field, obj))
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1686, in prepare_value
    return field.get_db_prep_save(value, connection=self.connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 1013, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2610, in get_db_prep_value
    value = self.get_prep_value(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2605, in get_prep_value
    return self.to_python(value)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2579, in to_python
    parsed = parse_time(value)
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\utils\dateparse.py", line 95, in parse_time
    return datetime.time.fromisoformat(value).replace(tzinfo=None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: fromisoformat: argument must be str
ERROR 2024-05-12 00:21:43,875 basehttp 13560 10236 "GET /game/orel_reshka/ HTTP/1.1" 500 144130
ERROR 2024-05-12 00:22:05,000 log 13560 10236 Internal Server Error: /game/orel_reshka/
Traceback (most recent call last):
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py", line 14, in orel_reshka
    res.save()
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    for sql, params in self.as_sql():
                       ^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1745, in as_sql
    value_rows = [
                 ^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1746, in <listcomp>
    [
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1747, in <listcomp>
    self.prepare_value(field, self.pre_save_val(field, obj))
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1686, in prepare_value
    return field.get_db_prep_save(value, connection=self.connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 1013, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2610, in get_db_prep_value
    value = self.get_prep_value(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2605, in get_prep_value
    return self.to_python(value)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2579, in to_python
    parsed = parse_time(value)
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\utils\dateparse.py", line 95, in parse_time
    return datetime.time.fromisoformat(value).replace(tzinfo=None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: fromisoformat: argument must be str
ERROR 2024-05-12 00:22:05,000 basehttp 13560 10236 "GET /game/orel_reshka/ HTTP/1.1" 500 144130
ERROR 2024-05-12 00:22:07,187 log 13560 10236 Internal Server Error: /game/orel_reshka/
Traceback (most recent call last):
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py", line 14, in orel_reshka
    res.save()
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    for sql, params in self.as_sql():
                       ^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1745, in as_sql
    value_rows = [
                 ^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1746, in <listcomp>
    [
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1747, in <listcomp>
    self.prepare_value(field, self.pre_save_val(field, obj))
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1686, in prepare_value
    return field.get_db_prep_save(value, connection=self.connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 1013, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2610, in get_db_prep_value
    value = self.get_prep_value(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2605, in get_prep_value
    return self.to_python(value)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2579, in to_python
    parsed = parse_time(value)
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\utils\dateparse.py", line 95, in parse_time
    return datetime.time.fromisoformat(value).replace(tzinfo=None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: fromisoformat: argument must be str
ERROR 2024-05-12 00:22:07,187 basehttp 13560 10236 "GET /game/orel_reshka/ HTTP/1.1" 500 144130
INFO 2024-05-12 00:27:26,502 autoreload 13560 2436 C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py changed, reloading.
INFO 2024-05-12 00:27:27,812 autoreload 9068 5012 Watching for file changes with StatReloader
INFO 2024-05-12 00:27:32,342 basehttp 9068 3936 "GET /game/orel_reshka/ HTTP/1.1" 200 11
INFO 2024-05-12 00:29:29,067 basehttp 9068 13924 "GET /game/orel_reshka/ HTTP/1.1" 200 11
INFO 2024-05-12 00:29:32,423 basehttp 9068 13924 "GET /game/orel_reshka/ HTTP/1.1" 200 11
INFO 2024-05-12 00:29:33,824 basehttp 9068 13924 "GET /game/orel_reshka/ HTTP/1.1" 200 11
INFO 2024-05-12 00:29:35,498 basehttp 9068 13924 "GET /game/orel_reshka/ HTTP/1.1" 200 11
INFO 2024-05-12 00:29:37,004 basehttp 9068 13924 "GET /game/orel_reshka/ HTTP/1.1" 200 11
INFO 2024-05-12 00:29:38,707 basehttp 9068 13924 "GET /game/orel_reshka/ HTTP/1.1" 200 11
INFO 2024-05-12 00:29:40,395 basehttp 9068 13924 "GET /game/orel_reshka/ HTTP/1.1" 200 11
INFO 2024-05-12 00:29:42,077 basehttp 9068 13924 "GET /game/orel_reshka/ HTTP/1.1" 200 11
INFO 2024-05-12 00:29:43,774 basehttp 9068 13924 "GET /game/orel_reshka/ HTTP/1.1" 200 11
INFO 2024-05-12 00:29:45,609 basehttp 9068 13924 "GET /game/orel_reshka/ HTTP/1.1" 200 11
INFO 2024-05-12 00:29:47,144 basehttp 9068 13924 "GET /game/orel_reshka/ HTTP/1.1" 200 11
INFO 2024-05-12 00:36:11,460 autoreload 9068 5012 C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\models.py changed, reloading.
INFO 2024-05-12 00:37:48,467 autoreload 11276 4184 Watching for file changes with StatReloader
INFO 2024-05-12 00:37:55,268 basehttp 11276 2460 "GET /game/orel_reshka/ HTTP/1.1" 200 11
INFO 2024-05-12 00:38:02,789 basehttp 11276 2460 "GET /game/orel_reshka/ HTTP/1.1" 200 11
INFO 2024-05-12 00:38:06,098 basehttp 11276 2460 "GET /game/orel_reshka/ HTTP/1.1" 200 11
INFO 2024-05-12 00:38:12,315 basehttp 11276 2460 "GET /game/orel_reshka/ HTTP/1.1" 200 11
INFO 2024-05-12 00:38:14,752 basehttp 11276 2460 "GET /game/orel_reshka/ HTTP/1.1" 200 11
INFO 2024-05-12 00:38:16,810 basehttp 11276 2460 "GET /game/orel_reshka/ HTTP/1.1" 200 11
INFO 2024-05-12 00:38:18,979 basehttp 11276 2460 "GET /game/orel_reshka/ HTTP/1.1" 200 11
INFO 2024-05-12 00:38:20,923 basehttp 11276 2460 "GET /game/orel_reshka/ HTTP/1.1" 200 11
INFO 2024-05-12 00:38:23,028 basehttp 11276 2460 "GET /game/orel_reshka/ HTTP/1.1" 200 11
INFO 2024-05-12 00:38:25,017 basehttp 11276 2460 "GET /game/orel_reshka/ HTTP/1.1" 200 11
INFO 2024-05-12 00:38:28,173 basehttp 11276 2460 "GET /game/orel_reshka/ HTTP/1.1" 200 11
INFO 2024-05-12 00:55:55,203 autoreload 11276 4184 C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\models.py changed, reloading.
INFO 2024-05-12 00:55:55,965 autoreload 10524 13288 Watching for file changes with StatReloader
INFO 2024-05-12 00:57:13,014 autoreload 12336 6892 Watching for file changes with StatReloader
INFO 2024-05-12 00:57:22,114 basehttp 12336 7380 "GET /game/orel_reshka/ HTTP/1.1" 200 11
INFO 2024-05-12 00:57:25,074 basehttp 12336 7380 "GET /game/orel_reshka/ HTTP/1.1" 200 11
INFO 2024-05-12 00:57:25,940 basehttp 12336 7380 "GET /game/orel_reshka/ HTTP/1.1" 200 11
INFO 2024-05-12 00:57:27,480 basehttp 12336 7380 "GET /game/orel_reshka/ HTTP/1.1" 200 11
INFO 2024-05-12 00:57:28,281 basehttp 12336 7380 "GET /game/orel_reshka/ HTTP/1.1" 200 11
INFO 2024-05-12 00:57:29,802 basehttp 12336 7380 "GET /game/orel_reshka/ HTTP/1.1" 200 11
INFO 2024-05-12 10:58:45,014 autoreload 1084 11592 Watching for file changes with StatReloader
INFO 2024-05-12 10:59:54,864 autoreload 1084 11592 C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py changed, reloading.
INFO 2024-05-12 10:59:56,430 autoreload 14800 3920 Watching for file changes with StatReloader
INFO 2024-05-12 11:01:11,815 autoreload 14800 3920 C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py changed, reloading.
INFO 2024-05-12 11:01:12,920 autoreload 5692 7208 Watching for file changes with StatReloader
INFO 2024-05-12 11:01:38,032 autoreload 5692 7208 C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py changed, reloading.
INFO 2024-05-12 11:01:39,362 autoreload 10712 10212 Watching for file changes with StatReloader
INFO 2024-05-12 11:02:04,544 autoreload 10712 10212 C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py changed, reloading.
INFO 2024-05-12 11:02:06,541 autoreload 15044 5508 Watching for file changes with StatReloader
INFO 2024-05-12 11:02:26,130 autoreload 15044 5508 C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\urls.py changed, reloading.
INFO 2024-05-12 11:02:27,670 autoreload 8564 10640 Watching for file changes with StatReloader
INFO 2024-05-12 11:03:02,860 autoreload 8564 10640 C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\urls.py changed, reloading.
INFO 2024-05-12 11:03:04,040 autoreload 14524 14564 Watching for file changes with StatReloader
INFO 2024-05-12 11:03:22,972 basehttp 14524 13900 "GET /game/orel_reshka/ HTTP/1.1" 200 11
WARNING 2024-05-12 11:03:23,196 log 14524 13900 Not Found: /favicon.ico
INFO 2024-05-12 11:03:23,196 basehttp 14524 13900 - Broken pipe from ('127.0.0.1', 56179)
INFO 2024-05-12 11:03:31,808 basehttp 14524 7004 "GET /game/orel_reshka/ HTTP/1.1" 200 11
ERROR 2024-05-12 11:03:45,075 log 14524 7004 Internal Server Error: /game/get_last_val/
Traceback (most recent call last):
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py", line 29, in get_last_val
    val = Results.values()
          ^^^^^^^^^^^^^^
AttributeError: type object 'Results' has no attribute 'values'
ERROR 2024-05-12 11:03:45,081 basehttp 14524 7004 "GET /game/get_last_val/ HTTP/1.1" 500 68800
ERROR 2024-05-12 11:04:58,944 log 14524 7004 Internal Server Error: /game/get_last_val/
Traceback (most recent call last):
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py", line 29, in get_last_val
    val = Results.last_val()
          ^^^^^^^^^^^^^^
AttributeError: type object 'Results' has no attribute 'values'
ERROR 2024-05-12 11:04:58,960 basehttp 14524 7004 "GET /game/get_last_val/ HTTP/1.1" 500 68804
INFO 2024-05-12 11:04:59,252 autoreload 14524 14564 C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py changed, reloading.
INFO 2024-05-12 11:05:00,829 autoreload 10044 4424 Watching for file changes with StatReloader
INFO 2024-05-12 11:05:05,366 basehttp 10044 11864 "GET /game/get_last_val/ HTTP/1.1" 200 4
INFO 2024-05-12 11:05:18,030 autoreload 10044 4424 C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py changed, reloading.
INFO 2024-05-12 11:05:18,947 autoreload 1304 4088 Watching for file changes with StatReloader
INFO 2024-05-12 11:05:25,626 basehttp 1304 9908 "GET /game/get_last_val/ HTTP/1.1" 200 5
INFO 2024-05-12 11:06:21,424 autoreload 1304 4088 C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py changed, reloading.
INFO 2024-05-12 11:06:22,301 autoreload 9132 14352 Watching for file changes with StatReloader
INFO 2024-05-12 11:06:27,043 basehttp 9132 13632 "GET /game/get_last_val/ HTTP/1.1" 200 168
INFO 2024-05-12 11:06:38,287 basehttp 9132 13632 "GET /game/get_last_val/ HTTP/1.1" 200 168
INFO 2024-05-12 11:07:23,783 autoreload 9132 14352 C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\models.py changed, reloading.
INFO 2024-05-12 11:07:24,987 autoreload 9008 12976 Watching for file changes with StatReloader
INFO 2024-05-12 11:07:29,441 basehttp 9008 14260 "GET /game/get_last_val/ HTTP/1.1" 200 610
INFO 2024-05-12 11:08:55,573 autoreload 9008 12976 C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\models.py changed, reloading.
INFO 2024-05-12 11:08:56,770 autoreload 1692 12440 Watching for file changes with StatReloader
INFO 2024-05-12 11:09:19,608 basehttp 1692 8508 "GET /game/get_last_val/ HTTP/1.1" 200 168
INFO 2024-05-12 11:11:05,740 autoreload 1692 12440 C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\models.py changed, reloading.
INFO 2024-05-12 11:11:06,734 autoreload 11552 2368 Watching for file changes with StatReloader
INFO 2024-05-12 11:11:43,615 autoreload 11552 2368 C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\models.py changed, reloading.
INFO 2024-05-12 11:11:44,954 autoreload 3032 5788 Watching for file changes with StatReloader
INFO 2024-05-12 11:11:57,978 basehttp 3032 4424 "GET /game/get_last_val/ HTTP/1.1" 200 441
INFO 2024-05-12 11:12:01,567 basehttp 3032 4424 "GET /game/get_last_val/ HTTP/1.1" 200 441
INFO 2024-05-12 11:12:47,480 autoreload 3032 5788 C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py changed, reloading.
INFO 2024-05-12 11:12:49,935 autoreload 12272 3056 Watching for file changes with StatReloader
INFO 2024-05-12 11:13:06,013 autoreload 12272 3056 C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\models.py changed, reloading.
INFO 2024-05-12 11:13:07,603 autoreload 10032 13628 Watching for file changes with StatReloader
INFO 2024-05-12 11:13:12,922 basehttp 10032 10600 "GET /game/get_last_val/ HTTP/1.1" 200 4
INFO 2024-05-12 11:15:22,379 autoreload 10032 13628 C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py changed, reloading.
INFO 2024-05-12 11:15:23,261 autoreload 15248 13816 Watching for file changes with StatReloader
ERROR 2024-05-12 11:15:26,805 log 15248 1308 Internal Server Error: /game/get_last_val/
Traceback (most recent call last):
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py", line 30, in get_last_val
    return HttpResponse(''.join([v for v in val]))
                                ^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
ERROR 2024-05-12 11:15:26,805 basehttp 15248 1308 "GET /game/get_last_val/ HTTP/1.1" 500 68694
INFO 2024-05-12 11:17:21,652 autoreload 15248 13816 C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py changed, reloading.
INFO 2024-05-12 11:17:22,822 autoreload 14776 14612 Watching for file changes with StatReloader
ERROR 2024-05-12 11:17:25,528 log 14776 6168 Internal Server Error: /game/get_last_val/
Traceback (most recent call last):
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py", line 30, in get_last_val
    return HttpResponse(*val)
           ^^^^^^^^^^^^^^^^^^
TypeError: django.http.response.HttpResponse() argument after * must be an iterable, not NoneType
ERROR 2024-05-12 11:17:25,528 basehttp 14776 6168 "GET /game/get_last_val/ HTTP/1.1" 500 68766
ERROR 2024-05-12 11:18:42,707 log 14776 6168 Internal Server Error: /game/get_last_val/
Traceback (most recent call last):
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py", line 30, in get_last_val
    s = ''.join(v for v in val)
           ^^^^^^^^^^^^^^^^^^
TypeError: django.http.response.HttpResponse() argument after * must be an iterable, not NoneType
ERROR 2024-05-12 11:18:42,719 basehttp 14776 6168 "GET /game/get_last_val/ HTTP/1.1" 500 69062
INFO 2024-05-12 11:18:43,371 autoreload 14776 14612 C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py changed, reloading.
INFO 2024-05-12 11:18:44,181 autoreload 15152 14008 Watching for file changes with StatReloader
ERROR 2024-05-12 11:18:47,468 log 15152 5724 Internal Server Error: /game/get_last_val/
Traceback (most recent call last):
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py", line 30, in get_last_val
    s = ''.join(v for v in val)
               ^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
ERROR 2024-05-12 11:18:47,468 basehttp 15152 5724 "GET /game/get_last_val/ HTTP/1.1" 500 68894
ERROR 2024-05-12 11:19:14,075 log 15152 5724 Internal Server Error: /game/get_last_val/
Traceback (most recent call last):
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py", line 30, in get_last_val
    print(val)
              
TypeError: 'NoneType' object is not iterable
ERROR 2024-05-12 11:19:14,085 basehttp 15152 5724 "GET /game/get_last_val/ HTTP/1.1" 500 68997
INFO 2024-05-12 11:19:14,511 autoreload 15152 14008 C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py changed, reloading.
INFO 2024-05-12 11:19:15,391 autoreload 12372 14112 Watching for file changes with StatReloader
ERROR 2024-05-12 11:19:18,675 log 12372 7020 Internal Server Error: /game/get_last_val/
Traceback (most recent call last):
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py", line 31, in get_last_val
    s = ''.join(v for v in val)
               ^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
ERROR 2024-05-12 11:19:18,712 basehttp 12372 7020 "GET /game/get_last_val/ HTTP/1.1" 500 68884
INFO 2024-05-12 11:19:39,682 autoreload 12372 14112 C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py changed, reloading.
INFO 2024-05-12 11:19:40,672 autoreload 13896 8308 Watching for file changes with StatReloader
INFO 2024-05-12 11:19:42,591 basehttp 13896 10324 "GET /game/get_last_val/ HTTP/1.1" 200 4
INFO 2024-05-12 11:20:22,241 autoreload 13896 8308 C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py changed, reloading.
INFO 2024-05-12 11:20:23,042 autoreload 11904 172 Watching for file changes with StatReloader
ERROR 2024-05-12 11:20:26,064 log 11904 13276 Internal Server Error: /game/get_last_val/
Traceback (most recent call last):
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py", line 30, in get_last_val
    print(*val)
TypeError: print() argument after * must be an iterable, not NoneType
ERROR 2024-05-12 11:20:26,064 basehttp 11904 13276 "GET /game/get_last_val/ HTTP/1.1" 500 69031
INFO 2024-05-12 11:20:46,267 autoreload 11904 172 C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py changed, reloading.
INFO 2024-05-12 11:20:47,896 autoreload 1916 4804 Watching for file changes with StatReloader
INFO 2024-05-12 11:22:27,358 autoreload 1916 4804 C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\models.py changed, reloading.
INFO 2024-05-12 11:22:28,232 autoreload 14456 296 Watching for file changes with StatReloader
INFO 2024-05-12 11:22:50,821 autoreload 14456 296 C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py changed, reloading.
INFO 2024-05-12 11:22:52,429 autoreload 1244 11400 Watching for file changes with StatReloader
ERROR 2024-05-12 11:22:53,679 log 1244 11408 Internal Server Error: /game/get_last_val/
Traceback (most recent call last):
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py", line 31, in get_last_val
    s = ''.join(v for v in val)
        ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, Results found
ERROR 2024-05-12 11:22:53,679 basehttp 1244 11408 "GET /game/get_last_val/ HTTP/1.1" 500 69388
INFO 2024-05-12 11:23:36,025 autoreload 1244 11400 C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py changed, reloading.
INFO 2024-05-12 11:23:37,271 autoreload 1632 13304 Watching for file changes with StatReloader
INFO 2024-05-12 11:23:39,848 basehttp 1632 12496 "GET /game/get_last_val/ HTTP/1.1" 200 365
INFO 2024-05-12 11:24:12,764 autoreload 1632 13304 C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py changed, reloading.
INFO 2024-05-12 11:24:13,715 autoreload 13588 12068 Watching for file changes with StatReloader
INFO 2024-05-12 11:24:16,203 basehttp 13588 14304 "GET /game/get_last_val/ HTTP/1.1" 200 365
INFO 2024-05-12 11:24:20,745 basehttp 13588 14304 "GET /game/get_last_val/ HTTP/1.1" 200 365
INFO 2024-05-12 11:24:43,022 autoreload 13588 12068 C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py changed, reloading.
INFO 2024-05-12 11:24:44,269 autoreload 11636 15252 Watching for file changes with StatReloader
INFO 2024-05-12 11:24:46,498 basehttp 11636 8900 "GET /game/get_last_val/ HTTP/1.1" 200 377
INFO 2024-05-12 11:24:55,274 autoreload 11636 15252 C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py changed, reloading.
INFO 2024-05-12 11:24:56,171 autoreload 9080 9808 Watching for file changes with StatReloader
INFO 2024-05-12 11:25:14,555 autoreload 9080 9808 C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py changed, reloading.
INFO 2024-05-12 11:25:15,686 autoreload 9964 13632 Watching for file changes with StatReloader
INFO 2024-05-12 11:25:25,642 basehttp 9964 14244 "GET /game/get_last_val/ HTTP/1.1" 200 401
INFO 2024-05-12 11:25:26,034 autoreload 9964 13632 C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py changed, reloading.
INFO 2024-05-12 11:25:27,153 autoreload 12648 14960 Watching for file changes with StatReloader
INFO 2024-05-12 11:25:38,058 autoreload 12648 14960 C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py changed, reloading.
INFO 2024-05-12 11:25:39,417 autoreload 13376 3708 Watching for file changes with StatReloader
INFO 2024-05-12 11:25:40,541 basehttp 13376 11752 "GET /game/get_last_val/ HTTP/1.1" 200 385
INFO 2024-05-12 11:25:55,407 autoreload 13376 3708 C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\views.py changed, reloading.
INFO 2024-05-12 11:25:56,245 autoreload 7908 6372 Watching for file changes with StatReloader
INFO 2024-05-12 11:26:09,299 autoreload 7908 6372 C:\Users\A9219\PycharmProjects\Django\seminar_proj\newapp\models.py changed, reloading.
INFO 2024-05-12 11:26:10,076 autoreload 8544 12056 Watching for file changes with StatReloader
INFO 2024-05-12 11:26:13,206 basehttp 8544 14592 "GET /game/get_last_val/ HTTP/1.1" 200 775
INFO 2024-05-12 15:37:43,324 autoreload 9620 8044 Watching for file changes with StatReloader
INFO 2024-05-12 15:37:58,937 basehttp 9620 1084 "GET /blog HTTP/1.1" 301 0
ERROR 2024-05-12 15:37:59,022 log 9620 6740 Internal Server Error: /blog/
Traceback (most recent call last):
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: create_author() takes 0 positional arguments but 1 was given
ERROR 2024-05-12 15:37:59,022 basehttp 9620 6740 "GET /blog/ HTTP/1.1" 500 65925
INFO 2024-05-12 15:39:10,701 autoreload 9620 8044 C:\Users\A9219\PycharmProjects\Django\seminar_proj\blogapp\views.py changed, reloading.
INFO 2024-05-12 15:39:11,553 autoreload 14660 400 Watching for file changes with StatReloader
ERROR 2024-05-12 15:39:14,748 log 14660 5776 Internal Server Error: /blog/
Traceback (most recent call last):
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\A9219\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view blogapp.views.create_author didn't return an HttpResponse object. It returned None instead.
ERROR 2024-05-12 15:39:14,748 basehttp 14660 5776 "GET /blog/ HTTP/1.1" 500 70481
INFO 2024-05-12 15:40:35,956 autoreload 14660 400 C:\Users\A9219\PycharmProjects\Django\seminar_proj\blogapp\views.py changed, reloading.
INFO 2024-05-12 15:40:36,872 autoreload 13456 11136 Watching for file changes with StatReloader
INFO 2024-05-12 15:41:07,672 basehttp 13456 11736 "GET /blog/ HTTP/1.1" 200 88
INFO 2024-05-12 15:41:56,315 autoreload 13456 11136 C:\Users\A9219\PycharmProjects\Django\seminar_proj\blogapp\views.py changed, reloading.
INFO 2024-05-12 15:41:57,180 autoreload 14244 7980 Watching for file changes with StatReloader
INFO 2024-05-12 15:42:02,378 basehttp 14244 6948 "GET /blog/ HTTP/1.1" 200 95
INFO 2024-05-12 15:44:00,537 autoreload 14244 7980 C:\Users\A9219\PycharmProjects\Django\seminar_proj\blogapp\views.py changed, reloading.
INFO 2024-05-12 15:44:01,470 autoreload 9408 6896 Watching for file changes with StatReloader
INFO 2024-05-12 15:44:04,595 basehttp 9408 9896 "GET /blog/ HTTP/1.1" 200 107
INFO 2024-05-12 15:50:57,723 autoreload 9408 6896 C:\Users\A9219\PycharmProjects\Django\seminar_proj\blogapp\views.py changed, reloading.
INFO 2024-05-12 15:50:59,604 autoreload 11600 12196 Watching for file changes with StatReloader
INFO 2024-05-12 15:51:01,140 basehttp 11600 14224 "GET /blog/ HTTP/1.1" 200 100
INFO 2024-05-12 15:51:04,140 basehttp 11600 14224 "GET /blog/ HTTP/1.1" 200 102
INFO 2024-05-12 15:51:46,444 autoreload 11600 12196 C:\Users\A9219\PycharmProjects\Django\seminar_proj\blogapp\urls.py changed, reloading.
INFO 2024-05-12 15:51:47,742 autoreload 11704 14928 Watching for file changes with StatReloader
INFO 2024-05-12 15:51:49,197 basehttp 11704 10704 "GET /blog/ HTTP/1.1" 200 15
INFO 2024-05-12 15:52:21,188 basehttp 11704 10704 "GET /blog/create_author HTTP/1.1" 200 101
INFO 2024-05-12 15:53:24,402 basehttp 11704 10704 "GET /blog/create_author HTTP/1.1" 200 98
INFO 2024-05-12 15:53:25,337 basehttp 11704 10704 "GET /blog/create_author HTTP/1.1" 200 104
INFO 2024-05-12 15:53:26,423 basehttp 11704 10704 "GET /blog/create_author HTTP/1.1" 200 103
INFO 2024-05-12 15:53:28,268 basehttp 11704 10704 "GET /blog/create_author HTTP/1.1" 200 100
INFO 2024-05-12 15:53:29,303 basehttp 11704 10704 "GET /blog/create_author HTTP/1.1" 200 100
INFO 2024-05-12 15:53:30,312 basehttp 11704 10704 "GET /blog/create_author HTTP/1.1" 200 98
INFO 2024-05-13 00:42:55,265 autoreload 616 3532 Watching for file changes with StatReloader
INFO 2024-05-13 00:43:07,110 basehttp 616 1304 "GET /blog/create_author HTTP/1.1" 200 94
INFO 2024-05-13 00:43:10,398 basehttp 616 1304 "GET /blog/ HTTP/1.1" 200 15
INFO 2024-05-13 00:43:18,845 basehttp 616 1304 "GET /shop/ HTTP/1.1" 200 30
WARNING 2024-05-13 00:43:54,456 log 616 1304 Not Found: /shop/get_all_products/
WARNING 2024-05-13 00:43:54,456 basehttp 616 1304 "GET /shop/get_all_products/ HTTP/1.1" 404 2853
INFO 2024-05-13 00:44:08,551 basehttp 616 1304 "GET /shop/ HTTP/1.1" 200 30
INFO 2024-05-13 00:46:25,731 autoreload 616 3532 C:\Users\A9219\PycharmProjects\Django\seminar_proj\shopapp\views.py changed, reloading.
INFO 2024-05-13 00:46:26,885 autoreload 9768 12156 Watching for file changes with StatReloader
